version: '2'
services:
    jdemo2-app:
        image: jdemo2
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jdemo2-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jdemo2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jdemo2-mongodb:
        extends:
            file: mongodb.yml
            service: jdemo2-mongodb
